### ISSUE TITLE
Redirect not appending path in version 2.7a

### ISSUE THREAD

**Issue by kieranjwelch** [goochjj/pound#2]
Hi,

We are trialling version 2.7a of Pound with a view of pushing it to our production environment to benefit from the fixes to poundctl.

I've noticed during our testing that 'Redirect' is no longer appending the path to the end of the URL.

This is our configuration, as an example:

```
Service
    HeadRequire "Host: stable.thinkleicestershire.co.uk"
    Redirect "https://stable.thinkleicestershire.co.uk"
End
```

With v2.6, if we visit http://stable.thinkleicestershire.co.uk/potato, we are redirected to https://stable.thinkleicestershire.co.uk/potato successfully.

In 2.7a, if we visit http://stable.thinkleicestershire.co.uk/potato, we are redirected to https://stable.thinkleicestershire.co.uk

Is this a known issue, is it resolved in 2.7b, or 2.7c?

From your documentation, it seems to suggest this is a bug:

Redirect [code] "url"
The address the client is redirected to is determined by the actual
url you specify: if it is a "pure" host (i.e. with no path) then the client will be redirected to the host you specified, with the original request path appended. If your url does contain a path then the request path is ignored.
Examples: if you specified
Redirect "http://abc.example"

and the client requested http://xyz/a/b/c then it will be redirected to http://abc.example/a/b/c, but if you specified

Redirect "http://abc.example/index.html"

it will be sent to http://abc.example/index.html.

**Comment by goochjj** [comment]
If you're using one of the stage for upstream branches, you want RedirectAppend instead of Redirect.  If you're using stock v2.7a, I don't see anything from 2.6 to 2.7a that would affect redirects in any way.  If you're running stock v2.7a you're better off posting to the pound mailing list. See http://www.apsis.ch/pound/index_html

**Comment by kieranjwelch** [comment]
Thanks for getting back to me so quickly!

We are indeed using the stage for upstream branch.

I presume the behaviour has been changed so 'Redirect' does exactly that, and no longer appends, whereas 'RedirectAppend' does what 'Redirect' used to do?

If so, that sounds great. I'll try changing our config and hopefully that'll resolve the issue.

Thanks again.

Kieran

**Comment by kieranjwelch** [comment]
Tested and working perfectly using 'RedirectAppend' rather than 'Redirect'. Thanks!

Is there any benefit to recompiling and using 2.7c rather than 2.7a?

**Comment by goochjj** [comment]
stage_for_upstream/v2.7c is based on v2.7b stock, plus my array of patches. (One of which implements Redirect vs RedirectAppend vs RedirectDynamic)  There were a bunch of changes in v2.7b, but if you're running my stage_for_upstream branch, you already have all of them.

This is due to those branches having more features than the stock vendor supplied source.  You'd want to make sure you're looking at the pound manpage from the source dir... Which does, for instance, spell out the redirectappend option.  (Can't just hit linux.die.net)
