### ISSUE TITLE
RedirectAppend changing URL encoding

### ISSUE THREAD

**Issue by kieranjwelch** [goochjj/pound#3]
I've noticed a slight issue whilst using 'RedirectAppend'.

For example, if we have a registration verification link sent via e-mail, using the http protocol, our pound is configured to 'RedirectAppend' from http to https.

ListenHTTP
Service
HeadRequire "Host: www.example.com"
RedirectAppend "https://www.example.com"
End
End

The link sent via e-mail is, for example:

http://www.example.com/Account/Welcome?e=test123@example.com&v=003c3086-e5e3-4ddb-b44d-b1d8c29ba76a

However, when pound redirectappends this url to HTTPS, the URL encoding is changed:

https://www.example.com/Account/Welcome?e%3dtest123%40example.com&v%3d003c3086-e5e3-4ddb-b44d-b1d8c29ba76a

Is this by design? It didn't behave like this in v2.6 when using 'Redirect' (which automatically appended the URL)

Thanks,

Kieran

**Comment by shabbirh** [comment]
This looks like it is URL encoding the query string portion and replacing the "=" with the encoded value (%3d) - weird.

I'll take a look at the http.c and see if there is anything strange going on there.

Warm Regards,

Shabbir

**Comment by goochjj** [comment]
It would be part of this commit https://github.com/goochjj/pound/commit/e731eaa9a6b039d9a43ab9b8b8f79c4cb8b578c9

Looks to me like I'm URL encoding the resulting redirect.  I believe, IIRC, the concern was that once we get to this portion of the thr_http workflow, we've already url-decoded the URL... Which means things that were passed encoded before (i.e. %20, %3d, etc), have since been un-encoded. So I wouldn't want the redirect to have things that should be encoded now passed verbatim.

Though, I suppose what it's doing now isn't appropriate either, since it's encoding things that weren't encoded in the original request.

I'd have to dig through it again to see what the options were. Unless someone wants to fix and issue a pull request!

**Comment by goochjj** [comment]
Actually I think it's somewhere in the redirect_reply that's causing it.  Are you seeing this in the actual redirect, or the HTML page causing it?

**Comment by goochjj** [comment]
May be enough to add || url[i] == '=' in redirect_reply, around line 46, so  ='s are escaped.

**Comment by kieranjwelch** [comment]
I'm seeing this behaviour in the browser when we visit the URL I provided above (obviously not with that domain name). We've also got Pound v2.6 running on the same site and we don't see this behaviour on that version. I can't really tell you more than that but happy to provide further information if needed.

Shabbir - you want to have a look at this?

**Comment by kieranjwelch** [comment]
I have now issued a pull request which includes a fix for this bug, for the 2.7c branch.
